### ISSUE TITLE
101-crackme task

### ISSUE THREAD

**Issue by tazy-dev** [Aksaim-mohamed-amin/alx-low_level_programming#1]
hi Akasim Mohamed
I want to say your medium post about this task really helped in understanding what I have to do
I looked at your code it makes perfect sense except one part
why mod 78 (%78)
what is special about it
or its arbitrary and I can set any number
.thank you for your time

**Comment by Aksaim-mohamed-amin** [comment]
Hello, I hope you're well.

I'm delighted to hear that my Medium post aided your understanding of this task. I value your engagement and inquisitiveness regarding the code.

The rand() function generates random numbers, and by utilizing the modulo operator "%," we can control the range of these generated numbers. For instance, in the line "password[i] = rand() % 78," this ensures that all generated numbers are confined to the range of 0 to 78. Upon adding the value of '0' (48 in ASCII), these numbers then fit into the acceptable character range for passwords (48 to 126 in ASCII).

Using rand() % 78 is vital, as otherwise, the generated number might exceed the permissible character range for passwords or, even worse, extend beyond the bounds of ASCII table values.

hope this will be helpful, if you have any other questions feel free to contact me.

**Comment by tazy-dev** [comment]
oh thanks a lot
